### ISSUE TITLE
Find out why app crashes under load

### ISSUE THREAD

**Issue by vpp** [vpp/timeoff-management#22]
Play with "siege" to see why under heavy load the app is crashing.

**Comment by vpp** [comment]
As those intermittent errors on travis become annoying:

Basic leave request
Unhandled rejection Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:690:11)
    at ServerResponse.header (/home/travis/tom/node_modules/express/lib/response.js:662:10)
    at ServerResponse.res.location (/home/travis/tom/node_modules/express/lib/response.js:776:8)
    at ServerResponse.redirect (/home/travis/tom/node_modules/express/lib/response.js:815:8)
    at /home/travis/tom/lib/middleware/session_aware_redirect.js:26:21
    at errorUpdating (/home/travis/tom/node_modules/connect-session-sequelize/lib/connect-session-sequelize.js:81:7)
    at tryCatcher (/home/travis/tom/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/travis/tom/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/home/travis/tom/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/home/travis/tom/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/home/travis/tom/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/travis/tom/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/home/travis/tom/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:448:13)

**Comment by vpp** [comment]
Could be related to #28
